### ISSUE TITLE
Use huge page with tcmalloc not working properly

### ISSUE THREAD

**Issue by AmirHosseinTaghavi** [gperftools/gperftools#1098] opened 2019-04-08 18:54 UTC
Hi, I want to use huge page with tcmalloc but it doesn't work. I installed tcmalloc on fedora and I write a program that allocates few mbytes simply. then according to docs, I set TCMALLOC_MEMFS_MALLOC_PATH environment variable to hugetlbfs mounted path and compile the program as follows:
`gcc -o test test.c -ltcmalloc`
by running this program, it doesn't return any error but no change happened in the hugetlbfs when I see huge pages status in /proc/meminfo. 
Is there any bug here or I just miss something?

**Comment by alk** [comment] 2019-04-21 17:30
This is likely duplicate of issue #824. Are you linking tcmalloc statically?

Otherwise, I was able to verify that tcmalloc in shared library works.

I.e. for test I did:

$ echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

$ TCMALLOC_MEMFS_MALLOC_PATH=/dev/hugepages/mem-bench ./malloc_bench

**Comment by Jianlin-lv** [comment] 2021-05-12 09:23
I also wrote a toy program to allocate hugepages through tcmalloc.
Transparent HugePage is available in my test environment, but the system-wide reserved HugePage cannot be used.

My program:

```
# gcc -o hp-malloc hp.c  -ltcmalloc
# ldd hp-malloc
        linux-vdso.so.1 (0x00007fffb68cd000)
        libtcmalloc.so.4 => /usr/local/lib/libtcmalloc.so.4 (0x00007f19f5d71000)
```

**Test for  Transparent Hugepage:**

Step1, enable transparent_hugepage
`# echo always > /sys/kernel/mm/transparent_hugepage/enabled
`
Step2: run toy program
`# ./hp-malloc
`
Step3: observe  map info of  hp-malloc

```
# cat /proc/`ps aux | grep hp-malloc | grep -v color | tr -s ' '| cut -d ' ' -f 2`/smaps |grep -A 20 heap
5619d5f52000-5619d7280000 rw-p 00000000 00:00 0                          [heap]
Size:              19640 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:               12568 kB
Pss:               12568 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:     12568 kB
Referenced:        12568 kB
Anonymous:         12568 kB
LazyFree:              0 kB
AnonHugePages:     10240 kB			// anonymous transparent huge pages
ShmemPmdMapped:        0 kB
FilePmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
```

**Test for System-wide reserved hugepage:**


Step1,  system info

```
# mount |grep -i huge
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)

# cat /proc//meminfo  |grep -i huge
AnonHugePages:    663552 kB
ShmemHugePages:        0 kB
FileHugePages:         0 kB
HugePages_Total:    2048
HugePages_Free:     1935
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:         4194304 kB
```


Step2: disable transparent_hugepage

`# echo never >/sys/kernel/mm/transparent_hugepage/enabled
`

Step3: run toy program

`# TCMALLOC_MEMFS_MALLOC_PATH=/dev/hugepages ./hp-malloc
`

Step4: observe  map info of  hp-malloc   and system huge info

```
# cat /proc/`ps aux | grep hp-malloc | grep -v color | tr -s ' '| cut -d ' ' -f 2`/smaps |grep -A 20 heap
55fe98777000-55fe99180000 rw-p 00000000 00:00 0                          [heap]
Size:              10276 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                2100 kB
Pss:                2100 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:      2100 kB
Referenced:         2100 kB
Anonymous:          2100 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
```


System-wide reserved hugepage status has not changed.
My gperftools version: 2.9.1

How to malloc memory from reserved hugepage, did I do something wrong?

**Closed** 2023-07-10 02:35 UTC
