### ISSUE TITLE
tcmalloc is trying to keep everything allocated for longer

### ISSUE THREAD

**Issue by coder-saab001** [gperftools/gperftools#1465] opened 2023-12-10 07:07 UTC
I am working on an application which is reading continuously from network and let's say storing it somewhere. I am reading in say 1 MB chunks again and again. I want the tcmalloc memory of previous iteration to be freed before next read iteration. What I can see now is it takes about ~1 sec for tcmalloc to free the previously allocated memory. Is there any way to tweak this default behaviour of tcmalloc?

**Comment by alk** [comment] 2023-12-10 18:13
Looks like semi-duplicate of #1466 . But do reopen if you can add something.

**Closed by alk** 2023-12-10 18:13 UTC

**Comment by coder-saab001** [comment] 2023-12-10 19:55
Not a duplicate actually. This is not about cache. Its about the aggresiveness with which tcmalloc is releasing previously allocated memory. I am reading in chunks in a loop and writing it somewhere. Now, before next read iteration, I want previous one to be completely cleared from the memory.

**Comment by coder-saab001** [comment] 2023-12-10 19:56
Can re-open an issue closed by contributor.

**Comment by alk** [comment] 2023-12-10 20:09
Can or cannot?

If you require such guarantee, then prepare to manage this bit of memory manually (via mmap or similar). But, frankly, I strongly suspect you should consider wanting something else (people are usually fine with some freelists headroom; so I sense misunderstanding)

**Comment by coder-saab001** [comment] 2023-12-10 20:37
Hmmm. Yeah it can't 
Let me try once again. Say my base memory consumption is 20MB and additional 16MB I am reading. The total memory consumption should be 36MB. But, with current model, it is going to around 100MB, because tcmalloc is not releasing memory immediately.

When tried having a sleep of 1 sec between the loop, the memory consumption is exact 36MB. But ofcourse, we don't want that sleep.
