### ISSUE TITLE
windows' snprint recurses back to malloc (was: tcmalloc spinlock reentrant cause program freeze)

### ISSUE THREAD

**Issue by luyt86** [gperftools/gperftools#1387] opened 2023-02-23 06:15 UTC
![image](https://user-images.githubusercontent.com/11455001/220833050-cacc30d7-e706-450c-a2cd-b63c76986c7d.png)

**Comment by alk** [comment] 2023-07-09 22:20
Thanks for reporting this. Looks like we'll have to take portable snprintf somewhere and use that instead of trusting OS.

**Comment by alk** [comment] 2023-07-22 22:09
Well, this is more interesting than I originally understood. You somehow added heap profiler to tcmalloc minimal config. Said nothing about this and then reported bug that can only happen in this highly unusual state.

I don't mind adding snprintf implementation that does not touch errno, but I do mind when people file tickets trying to hide things from me. Or at least that is how it looks.

If I want to fix this or something like this, I ***require*** being able to reproduce.

Closing as invalid (open if you have something to add, including whatever modifications you've made)

**Closed by alk** 2023-07-22 22:09 UTC
Labels: bug, porting, windows
