### ISSUE TITLE
*** malloc_zone_unregister() failed on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by zchee** [gperftools/gperftools#827] opened 2016-09-03 12:38 UTC
As a https://github.com/jemalloc/jemalloc/pull/427, occur `malloc_zone_unregister` on macOS Sierra 10.12.

I have tested with this diff, will work fine(but I have not C language experience).
Can I send this pull request? or Do you have any idea?

```diff
diff --git a/src/libc_override_osx.h b/src/libc_override_osx.h
index b801f22..37c96c6 100644
--- a/src/libc_override_osx.h
+++ b/src/libc_override_osx.h
@@ -211,6 +211,34 @@ extern "C" {
   size_t malloc_usable_size(void* p)     { return tc_malloc_size(p); }
 }  // extern "C"
 
+static malloc_zone_t *get_default_zone()
+{
+	malloc_zone_t **zones = NULL;
+	unsigned int num_zones = 0;
+
+	/*
+	 * On OSX 10.12, malloc_default_zone returns a special zone that is not
+	 * present in the list of registered zones. That zone uses a "lite zone"
+	 * if one is present (apparently enabled when malloc stack logging is
+	 * enabled), or the first registered zone otherwise. In practice this
+	 * means unless malloc stack logging is enabled, the first registered
+	 * zone is the default.
+	 * So get the list of zones to get the first one, instead of relying on
+	 * malloc_default_zone.
+	 */
+        if (KERN_SUCCESS != malloc_get_all_zones(0, NULL, (vm_address_t**) &zones,
+	                                         &num_zones)) {
+		/* Reset the value in case the failure happened after it was set. */
+		num_zones = 0;
+	}
+
+	if (num_zones)
+		return zones[0];
+
+	return malloc_default_zone();
+}
+
+
 static void ReplaceSystemAlloc() {
   static malloc_introspection_t tcmalloc_introspection;
   memset(&tcmalloc_introspection, 0, sizeof(tcmalloc_introspection));
@@ -273,7 +301,7 @@ static void ReplaceSystemAlloc() {
   // zone.  The default zone is then re-registered to ensure that
   // allocations made from it earlier will be handled correctly.
   // Things are not guaranteed to work that way, but it's how they work now.
-  malloc_zone_t *default_zone = malloc_default_zone();
+  malloc_zone_t *default_zone = get_default_zone();
   malloc_zone_unregister(default_zone);
   malloc_zone_register(default_zone);
 }
```

**Comment by dralves** [comment] 2016-09-20 22:43
I'm hitting this too, trying to build Apache Kudu (which uses gperftools). Any way we can get this merged in?

**Comment by alk** [comment] 2016-09-22 16:41
On Tue, Sep 20, 2016 at 3:43 PM, David Ribeiro Alves <
notifications@github.com> wrote:

> I'm hitting this too, trying to build Apache Kudu (which uses gperftools).
> Any way we can get this merged in?
>

I'll take a look this Saturday. Meanwhile, you can help by testing if this
patch helps your case.

**Comment by alk** [comment] 2016-09-22 16:45
Looks like there is already patch merged for that in kudu. Which implies that people tested it.

**Comment by dralves** [comment] 2016-09-22 16:45
@alk great, thanks!
As you can see by the linked issue we apply this patch verbatim to gperftools 2.2.1 in our build. I can confirm It solves the aforementioned issue.

**Comment by alk** [comment] 2016-09-22 16:46
Thanks. BTW, why gperftools 2.2.1? Are you having issues with later releases ?

**Comment by alk** [comment] 2016-09-25 02:57
Should be fixed now (but I haven't tested).

**Closed by alk** 2016-09-25 02:57 UTC

**Comment by zchee** [comment] 2016-09-25 02:59
@alk Thanks! I'll test it :)
