### ISSUE TITLE
gcc 11 invalid 'static_cast' from type 'std::nullptr_t' to type 'uintptr_t'

### ISSUE THREAD

**Issue by xiedeacc** [gperftools/gperftools#1336] opened 2022-05-24 08:49 UTC
gperftools:2.9.1
src/heap-checker.cc:1171:35: error: invalid 'static_cast' from type 'std::nullptr_t' to type 'uintptr_t' {aka 'long unsigned int'}

**Comment by alk** [comment] 2022-05-31 03:02
Fixed. Duplicate of issue #1338

**Closed** 2022-05-31 03:02 UTC
