### ISSUE TITLE
How to fill newed memory for debugging?

### ISSUE THREAD

**Issue by f18m** [gperftools/gperftools#867] opened 2017-01-23 15:36 UTC
Hi,
this issue is very similar to #866 : for debugging I am using a hooked callback with
   MallocHook::AddNewHook()
and I memset the pointer there to the value 0xCD, the Microsoft standard for newly-allocated memory.

However there is a problem with this approach: calloc() calls will trigger the execution of:

`
extern "C" PERFTOOLS_DLL_DECL void* tc_calloc(size_t n,
                                              size_t elem_size) __THROW {
  void* result = do_calloc(n, elem_size);
  MallocHook::InvokeNewHook(result, n * elem_size);
  return result;
}
`

which will calloc the memory, and then call the memory hook. From my memory hook, I overwrite memory contents since I have no way to distinguish if the memory hook is called from new()/malloc() or from calloc().

Can you suggest how to solve this issue?
Would be possible to inform the hook function that it's inside a calloc() call?

Thanks,
Francesco

**Comment by alk** [comment] 2017-01-23 18:15
Closing as duplicate of #866.

**Closed by alk** 2017-01-23 18:15 UTC
