### ISSUE TITLE
tcmalloc_minimal_unittest compiled by MSVC2015 for x86 platform on Win10 fails

### ISSUE THREAD

**Issue by HolyWu** [gperftools/gperftools#745] opened 2015-11-22 16:18 UTC
On x86 platform, `tcmalloc_minimal_unittest` gives the following message and crashes:
```
Testing empty allocation
Testing STL use
Sanity-testing all the memory allocation functions
Check failed: g_DeleteHook_calls > 0
```

On x64 platform, although `tcmalloc_minimal_unittest` doesn't crash and gives a **PASS** at the end, it keeps outputting messages to stderr during testing like the following:
```
tcmalloc: large alloc 18446744073709453312 bytes == 0000000000000000 @  00007FF6D05B70FD 00007FF6D05B711A 00007FF6D05B2794 00007FF6D05B27EA 00007FF6D05B494C 00007FF6D05B4B20 00007FF6D05B7370 00007FFF445B8102 00007FFF46E2C264
```
or
```
tcmalloc: large alloc 0 bytes == 0000000000000000 @  00007FF6D05B225F 00007FF6D05B4A77 00007FF6D05B4B20 00007FF6D05B7370 00007FFF445B8102 00007FFF46E2C264
```
etc. I am not sure if it's normal and intended.

**Comment by alk** [comment] 2015-11-22 19:22
large alloc messages are normal and intended.

But failure on 32 bits is not normal. May I ask you to indicate at which line tcmalloc_unittest.cc it fails? Also what is exact version you are testing ?

**Comment by alk** [comment] 2015-11-22 19:23
This might be known issue. See #719

**Comment by HolyWu** [comment] 2015-11-23 11:39
The version I am testing is from the latest commit 64892ae730b704a7f3f23bd8eaeaf206901df201 at the moment. It fails at line 1194 ([screenshot](http://i.imgur.com/sZtYwiF.png)). If I comment that line out, the rest testings succeed and give a PASS at the end.

**Comment by alk** [comment] 2016-03-06 17:58
Yes, that is duplicate of #719

**Closed by alk** 2016-03-06 17:58 UTC

**Comment by xiaowei0516** [comment] 2016-05-03 08:06
I encountered the same problem.  PERFTOOLS_NO_ALIGNED_MALLOC is or not  defined. 
I defined it, run passed.
