### ISSUE TITLE
Build fails with CLang 3.8 ("sized operator delete")

### ISSUE THREAD

**Issue by iarspider** [gperftools/gperftools#804] opened 2016-05-31 12:39 UTC
Error message:

```
libtool: link: /afs/cern.ch/sw/lcg/external/llvm/3.8/x86_64-slc6/bin/clang++ -DNO_TCMALLOC_SAMPLES -g -O2 -o low_level_alloc_unittest src/base/low_level_alloc_unittest-low_level_alloc.o src/low_level_alloc_unittest-malloc_hook.o src/tests/low_level_alloc_unittest-low_level_alloc_unittest.o  ./.libs/libspinlock.a ./.libs/libsysinfo.a ./.libs/liblogging.a ./.libs/libmaybe_threads.a /afs/cern.ch/sw/lcg/contrib/gcc/4.9.3/x86_64-slc6/lib/../lib64/libstdc++.so -Wl,-rpath -Wl,/afs/cern.ch/sw/lcg/contrib/gcc/4.9.3/x86_64-slc6/lib/../lib64 -Wl,-rpath -Wl,/afs/cern.ch/sw/lcg/contrib/gcc/4.9.3/x86_64-slc6/lib/../lib64
./.libs/libsysinfo.a(sysinfo.o): In function `ProcMapsIterator::~ProcMapsIterator()':
/var/build/jenkins/workspace/lcg_experimental/BUILDTYPE/Release/COMPILER/clang38/LABEL/slc6-physical/build/externals/gperftools-2.5/src/gperftools/2.5/src/base/sysinfo.cc:519: undefined reference to `operator delete(void*, unsigned long)'
./.libs/libsysinfo.a(sysinfo.o): In function `tcmalloc::FillProcSelfMaps(char*, int, bool*)':
/var/build/jenkins/workspace/lcg_experimental/BUILDTYPE/Release/COMPILER/clang38/LABEL/slc6-physical/build/externals/gperftools-2.5/src/gperftools/2.5/src/base/sysinfo.cc:519: undefined reference to `operator delete(void*, unsigned long)'
/var/build/jenkins/workspace/lcg_experimental/BUILDTYPE/Release/COMPILER/clang38/LABEL/slc6-physical/build/externals/gperftools-2.5/src/gperftools/2.5/src/base/sysinfo.cc:519: undefined reference to `operator delete(void*, unsigned long)'
./.libs/libsysinfo.a(sysinfo.o): In function `tcmalloc::DumpProcSelfMaps(int)':
/var/build/jenkins/workspace/lcg_experimental/BUILDTYPE/Release/COMPILER/clang38/LABEL/slc6-physical/build/externals/gperftools-2.5/src/gperftools/2.5/src/base/sysinfo.cc:519: undefined reference to `operator delete(void*, unsigned long)'
/var/build/jenkins/workspace/lcg_experimental/BUILDTYPE/Release/COMPILER/clang38/LABEL/slc6-physical/build/externals/gperftools-2.5/src/gperftools/2.5/src/base/sysinfo.cc:519: undefined reference to `operator delete(void*, unsigned long)'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [low_level_alloc_unittest] Error 1
```

I think this is related to [this](https://llvm.org/bugs/show_bug.cgi?id=22951#c2):

> This was introduced by r229241 - Revise the implementation logic of sized deallocation: Do not automatically generate weak definitions of the sized operator delete (in terms of unsized operator delete). Instead, provide the funcitonality via a new compiler flag, -fdef-sized-delete

**Comment by alk** [comment] 2016-06-26 01:31
Thanks for report. But I am not able to reproduce the problem. Is that clang-3.8 with it's own libc++ or something else? GNU/Linux ?

**Comment by iarspider** [comment] 2016-06-26 06:29
The build was performed on SLC6 machine, with libstdc++ from gcc 4.9. I'll check the suggestion in the linked bug report.

**Comment by alk** [comment] 2016-06-26 19:04
I would like to reproduce this. Can you please describe how you got clang 3.8 on that box?

**Comment by alk** [comment] 2016-07-16 02:33
Gentle ping. Can you please share more details on your exact setup? I would very much like to reproduce the problem

**Comment by iarspider** [comment] 2016-07-16 07:00
Hi,

the compiler was produced by a different person, and I'm waiting for her to
answer. I'll ask her again.

-- iarspider

**Comment by alk** [comment] 2016-08-27 19:01
Gentle, ping. In about month or so I plan to do sweep of all tickets. And I'll have to close this ticket if there is still no update.

**Comment by jdahm** [comment] 2017-10-24 21:35
I have the same issue here with both clang version 3.8.0 and 4.0.0: `gperftools/src/base/sysinfo.cc:550: undefined reference to 'operator delete(void*, unsigned long)'`

**Comment by alk** [comment] 2017-10-30 16:57
More details please. As soon as I can reproduce the problem, I will be able to help.

**Comment by msk** [comment] 2017-11-15 05:45
The same issue on OS X 10.11.6 with Apple LLVM version 7.3.0 (clang-703.0.29):
```
/bin/sh ./libtool  --tag=CXX   --mode=link g++ -DNO_TCMALLOC_SAMPLES -D_THREAD_SAFE  -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation   -g -O2 -version-info 8:5:4 -no-undefined  -Wl,-U,___lsan_ignore_object  -o libtcmalloc_minimal.la -rpath /usr/local/lib src/libtcmalloc_minimal_la-tcmalloc.lo    libtcmalloc_minimal_internal.la 
libtool: link: g++ -dynamiclib  -o .libs/libtcmalloc_minimal.4.dylib  src/.libs/libtcmalloc_minimal_la-tcmalloc.o   -Wl,-force_load,./.libs/libtcmalloc_minimal_internal.a   -g -O2 -Wl,-U -Wl,___lsan_ignore_object   -install_name  /usr/local/lib/libtcmalloc_minimal.4.dylib -compatibility_version 9 -current_version 9.5 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "operator delete(void*, unsigned long)", referenced from:
      TCMallocImplementation::~TCMallocImplementation() in libtcmalloc_minimal_la-tcmalloc.o
      SbrkSysAllocator::~SbrkSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      MmapSysAllocator::~MmapSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      DevMemSysAllocator::~DevMemSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      DefaultSysAllocator::~DefaultSysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-system-alloc.o)
      __GLOBAL__sub_I_symbolize.cc in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-symbolize.o)
      SysAllocator::~SysAllocator() in libtcmalloc_minimal_internal.a(libtcmalloc_minimal_internal_la-malloc_extension.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libtcmalloc_minimal.la] Error 1
```

**Comment by alk** [comment] 2018-08-06 00:29
Is that still relevant?

**Closed** 2023-07-10 03:07 UTC
