### ISSUE TITLE
deadlock in tcmalloc

### ISSUE THREAD

**Issue by Sangarshan** [gperftools/gperftools#1196] opened 2020-05-26 04:13 UTC
Hi, 
we are currently using gperftools 2.1. we observed deadlock in tcmalloc library as all threads waiting for spinlock.
@alk could you please confirm whether it is same as issue #535 

here are the details

Thread 3 (Thread 0x7f4a8a300700 (LWP 451164)):

#0 0x00007f4a93129b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4

#1 0x00007f4a93129a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4

#2 0x00007f4a93119c58 in tcmalloc::CentralFreeList::ReleaseToSpans(void*) ()

from /lib64/libtcmalloc.so.4

#3 0x00007f4a93119cbe in tcmalloc::CentralFreeList::ReleaseListToSpans(void*)

() from /lib64/libtcmalloc.so.4

#4 0x00007f4a93119df4 in tcmalloc::CentralFreeList::ShrinkCache(int, bool) ()

from /lib64/libtcmalloc.so.4

#5 0x00007f4a93119f1d in tcmalloc::CentralFreeList::MakeCacheSpace() ()

from /lib64/libtcmalloc.so.4

#6 0x00007f4a93119f98 in tcmalloc::CentralFreeList::InsertRange(void*, void*, int) () from /lib64/libtcmalloc.so.4

#7 0x00007f4a9311d408 in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) () from /lib64/libtcmalloc.so.4

#8 0x00007f4a9311d798 in tcmalloc::ThreadCache::Scavenge() ()

from /lib64/libtcmalloc.so.4

Thread 11 (Thread 0x7f4a820c5700 (LWP 454271)):

#0 0x00007f4a9311ae26 in tcmalloc::PageHeap::AllocLarge(unsigned long) ()

from /lib64/libtcmalloc.so.4

#1 0x00007f4a9311b591 in tcmalloc::PageHeap::New(unsigned long) ()

from /lib64/libtcmalloc.so.4

#2 0x00007f4a9310c462 in (anonymous namespace)::do_malloc_pages(tcmalloc::ThreadCache*, unsigned long) () from /lib64/libtcmalloc.so.4

#3 0x00007f4a9312cd56 in tc_realloc () from /lib64/libtcmalloc.so.4

Thread 15 (Thread 0x7f4a810c1700 (LWP 191875)):

#0 0x00007f4a93129b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4

#1 0x00007f4a93129a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4

#2 0x00007f4a9311a248 in tcmalloc::CentralFreeList::Populate() ()

from /lib64/libtcmalloc.so.4

#3 0x00007f4a9311a338 in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /lib64/libtcmalloc.so.4

#4 0x00007f4a9311a3d0 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4

#5 0x00007f4a9311d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4

#6 0x000000000148c72d in UTCTimestampUsec ()

at src/contrail-common/base/time_util.h:18

#7 GetCurrentTime ()

Thread 18 (Thread 0x7f4a804be700 (LWP 56246)):

#0  0x00007f4a93129b8b in base::internal::SpinLockDelay(int volatile*, int, int) () from /lib64/libtcmalloc.so.4
#1  0x00007f4a93129a8f in SpinLock::SlowLock() () from /lib64/libtcmalloc.so.4
#2  0x00007f4a9311a248 in tcmalloc::CentralFreeList::Populate() ()
   from /lib64/libtcmalloc.so.4
#3  0x00007f4a9311a338 in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) () from /lib64/libtcmalloc.so.4
#4  0x00007f4a9311a3d0 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) () from /lib64/libtcmalloc.so.4
#5  0x00007f4a9311d2a7 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int) () from /lib64/libtcmalloc.so.4
#6  0x00007f4a90b39a45 in std::locale::_Impl::_Impl(std::locale::_Impl const&, unsigned long) () from /lib64/libstdc++.so.6
#7  0x0000000000a465a1 in std::locale::locale<boost::date_time::time_facet<boost::posix_time::ptime, char, std::ostreambuf_iterator<char, std::char_traits<char> > > > (this=0x7f4a934e2de8 <tcmalloc::Static::pageheap_lock_>, __other=..., 
    __f=0x2) at /usr/include/c++/4.8.2/bits/locale_classes.tcc:47
#8  0x000000000f5a2a58 in ?? ()
#9  0x00007f4a804bd8c0 in ?? ()
#10 0x00007f4a804bd918 in ?? ()
#11 0x00007f4a804bd8c8 in ?? ()
#12 0x0000000000000000 in ?? ()

Regards,
Sangarshan

**Comment by alk** [comment] 2020-07-06 08:39
Since you are reporting this against very old version, I am going to close this. Reopen if we can reproduce the problem with latest code.

**Closed by alk** 2020-07-06 08:39 UTC
