### ISSUE TITLE
Undefined reference to `TCMallocGetenvSafe` on PPC and i386

### ISSUE THREAD

**Issue by msimberg** [gperftools/gperftools#1474] opened 2024-01-04 11:24 UTC
This error popped up when adding gperftools 2.14 to spack (full log: https://gitlab.spack.io/spack/spack/-/jobs/9711611#L937L):

```
libtool: link: /builds/spack/spack/lib/spack/env/gcc/g++ -std=gnu++11 -DNO_TCMALLOC_SAMPLES -g -O2 -o low_level_alloc_unittest src/base/low_level_alloc_unittest-low_level_alloc.o src/low_level_alloc_unittest-malloc_hook.o src/low_level_alloc_unittest-mmap_hook.o src/tests/low_level_alloc_unittest-low_level_alloc_unittest.o  ./.libs/libspinlock.a ./.libs/libsysinfo.a ./.libs/liblogging.a -lunwind
/bin/bash ./libtool  --tag=CXX   --mode=link /builds/spack/spack/lib/spack/env/gcc/g++ -std=gnu++11 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-result -fsized-deallocation -faligned-new   -DSTACKTRACE_IS_TESTED -g -O2 -export-dynamic -lunwind -o stacktrace_unittest src/tests/stacktrace_unittest-stacktrace_unittest.o src/stacktrace_unittest-stacktrace.o src/base/stacktrace_unittest-elf_mem_image.o src/base/stacktrace_unittest-vdso_support.o      -lunwind libspinlock.la libsysinfo.la liblogging.la liblogging.la libfake_stacktrace_scope.la  
libtool: link: /builds/spack/spack/lib/spack/env/gcc/g++ -std=gnu++11 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-result -fsized-deallocation -faligned-new -DSTACKTRACE_IS_TESTED -g -O2 -o stacktrace_unittest src/tests/stacktrace_unittest-stacktrace_unittest.o src/stacktrace_unittest-stacktrace.o src/base/stacktrace_unittest-elf_mem_image.o src/base/stacktrace_unittest-vdso_support.o -Wl,--export-dynamic  ./.libs/libspinlock.a ./.libs/libsysinfo.a ./.libs/liblogging.a ./.libs/libfake_stacktrace_scope.a -lunwind
/usr/bin/ld: ./.libs/liblogging.a(dynamic_annotations.o): in function `RunningOnValgrind':
/tmp/root/spack-stage/spack-stage-gperftools-2.14-yhb2lpga7yyb63xsmnvew4zncsdphkj7/spack-src/src/base/dynamic_annotations.cc:46: undefined reference to `TCMallocGetenvSafe'
collect2: error: ld returned 1 exit status
make: *** [Makefile:4410: stacktrace_unittest] Error 1
make: *** Waiting for unfinished jobs....
```

x86 builds seem to be fine. I don't have direct access to the PPC environment so I can't really do interactive debugging, but I can try out patches if that's helpful. Pinging @barracuda156 in case you have some ideas and/or debugging help since I've seen you test PPC builds before (apologies if you're not interested or don't have the time).

**Comment by spotaws** [comment] 2024-01-04 16:43
This seems to happen on Fedora Rawhide for i686 and ppc64le builds only... :/

**Comment by alk** [comment] 2024-01-04 16:51
Thanks for the ticket. Can I get logs from a one successful build (i.e. amd64 from description above succeeds)? I assume all the patchings and flags are same ?

Also while likely unrelated I find odd that you guys explicitly pass LDFLAGS=-lunwind and there seem to be some patching of configure script at least according to logs. Any details on whys? (they are most likely unrelated but who knows)

Also are guys saying I might be able to reproduce in say docker on i686 ?

**Comment by spotaws** [comment] 2024-01-04 16:52
Fedora's build log showing the ppc64le failure is here: https://kojipkgs.fedoraproject.org//work/tasks/6919/111246919/build.log
Same build succeeding on x86_64 is here: https://kojipkgs.fedoraproject.org//work/tasks/6917/111246917/build.log

**Comment by alk** [comment] 2024-01-04 16:56
Ah, on the failure itself, the most plausible thing (although it doesn't explain why it works on other arches) is that RunningOnValgrind is pulled from liblogging.a which calls into getenv-safe thingy from libsysinfo.a. But in link order libsysinfo.a is mentioned first. There used to be an well-known issue with static linking that too early .a in the link order might cause some .o to be "missed". Not sure if libtool is supposed to handle it somehow or not. And, again, it doesn't explain why it works elsewhere.

**Comment by alk** [comment] 2024-01-04 17:24
yes it has. And that is my point. libsysinfo.a is mentioned before liblogging.a.

But I also see that fedora thingy does -flto who knows if it might be related. When you said you think link order doesn't matter, are you saying you tried changing it ?

Are you able to try, just for the sake of trying, turning -flto off ?

Are you able to reproduce this issue locally? (Debian has schroot which makes it super-convenient to do i386 and other cross-architectures; you guys have anything similar?)

**Comment by alk** [comment] 2024-01-04 17:26
BTW on my debian sid I am able to cross compile ppc64le stacktrace_unittest:

```
$ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -fasynchronous-unwind-tables -fstack-clash-protection ' ./configure --disable-static --host=powerpc64le-linux-gnu
$ make stacktrace_unittest
```

**Comment by alk** [comment] 2024-01-04 17:30
thanks. Also if you're able to give me docker instructions (or even Dockerfile) with the environment where this is reproducible, then I'll be able to look closer.

**Comment by spotaws** [comment] 2024-01-04 17:41
When I set %_lto_cflags to %nil in the i686 build (it is normally set to -flto=auto -ffat-lto-objects), it does not change the outcome.

**Comment by spotaws** [comment] 2024-01-04 17:42
/builddir/build/BUILD/gperftools-2.14/src/base/dynamic_annotations.cc:46:(.text+0x3b): undefined reference to `TCMallocGetenvSafe'

**Comment by alk** [comment] 2024-01-04 18:07
ok. I am able to reproduce on Debian's i686-linux-gnu-g++. So hopefully I'll figure out soon what's up.

**Comment by spotaws** [comment] 2024-01-04 18:08
Apologies. I don't know of a good way to Dockerize Fedora rawhide, so I'm glad you could repro this on Debian. :)

**Comment by alk** [comment] 2024-01-04 18:13
So there is circular dependency between liblogging and libsysinfo. As I noted adding one more of each (manually, since libtool or maybe automake seems to be eating those dups) "works":

```
i686-linux-gnu-g++ -std=gnu++11 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-result -fsized-deallocation -faligned-new -fno-omit-frame-pointer -momit-leaf-frame-pointer -DSTACKTRACE_IS_TESTED -Og -ggdb3 -Wall -o stacktrace_unittest src/tests/stacktrace_unittest-stacktrace_unittest.o src/stacktrace_unittest-stacktrace.o src/base/stacktrace_unittest-elf_mem_image.o src/base/stacktrace_unittest-vdso_support.o -Wl,--export-dynamic  ./.libs/libspinlock.a ./.libs/libsysinfo.a ./.libs/liblogging.a ./.libs/libfake_stacktrace_scope.a ./.libs/libsysinfo.a ./.libs/liblogging.a
```

Still plenty puzzling and some way towards answers, but at least we got something.

**Comment by spotaws** [comment] 2024-01-04 18:36
I can also confirm that this "works" without errors for me (fedora rawhide i686):

`g++ -std=gnu++11 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-result -fsized-deallocation -faligned-new -fno-omit-frame-pointer -momit-leaf-frame-pointer -DSTACKTRACE_IS_TESTED -O2 -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-strict-aliasing -Wno-unused-local-typedefs -DTCMALLOC_LARGE_PAGES -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,pack-relative-relocs -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes -o stacktrace_unittest src/tests/stacktrace_unittest-stacktrace_unittest.o src/stacktrace_unittest-stacktrace.o src/base/stacktrace_unittest-elf_mem_image.o src/base/stacktrace_unittest-vdso_support.o -Wl,--export-dynamic  -lunwind ./.libs/libspinlock.a ./.libs/libsysinfo.a ./.libs/liblogging.a ./.libs/libsysinfo.a ./.libs/liblogging.a ./.libs/libfake_stacktrace_scope.a`

**Comment by alk** [comment] 2024-01-04 19:00
So there is at least one way to fix it. But I still mega-puzzled why it originally fails only on subset of architectures. Really puzzled there.

Here is what I have so far (feel free to test if you wish; I haven't yet decided if it'll be final fix or I'll try something else):

```
diff --git a/Makefile.am b/Makefile.am
index 143d5690..05ea6314 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -169,7 +169,7 @@ SYSINFO_INCLUDES = src/base/sysinfo.h \
 noinst_LTLIBRARIES += libsysinfo.la
 libsysinfo_la_SOURCES = src/base/sysinfo.cc \
                         $(SYSINFO_INCLUDES)
-libsysinfo_la_LIBADD = $(NANOSLEEP_LIBS)
+libsysinfo_la_LIBADD = $(NANOSLEEP_LIBS) liblogging.la
 
 # For MinGW, we use also have to use libwindows Luckily, we need the
 # windows.a library in exactly the same place we need spinlock.a
```

It sorta makes sense. We're telling libtool that sysinfo uses liblogging bits. But the way it ends up duplicating stuff in .a archive doesn't look very nice to me. So still thinking about this all.

**Comment by spotaws** [comment] 2024-01-04 19:17
I don't think that approach is correct. When I test that on Fedora Rawhide x86_64, it fails with:

```
/usr/bin/ld: lt1-dynamic_annotations.o (symbol from plugin): in function `RunningOnValgrind':
(.text+0x0): multiple definition of `RunningOnValgrind'; dynamic_annotations.o (symbol from plugin):(.text+0x0): first defined here
/usr/bin/ld: lt2-logging.o (symbol from plugin): in function `FLAG__namespace_do_not_use_directly_use_DECLARE_int32_instead::FLAGS_verbose':
(.text+0x0): multiple definition of `FLAG__namespace_do_not_use_directly_use_DECLARE_int32_instead::FLAGS_verbose'; logging.o (symbol from plugin):(.text+0x0): first defined here
/usr/bin/ld: lt2-logging.o (symbol from plugin): in function `FLAG__namespace_do_not_use_directly_use_DECLARE_int32_instead::FLAGS_verbose':
(.text+0x0): multiple definition of `RawOpenForWriting(char const*)'; logging.o (symbol from plugin):(.text+0x0): first defined here
/usr/bin/ld: lt2-logging.o (symbol from plugin): in function `FLAG__namespace_do_not_use_directly_use_DECLARE_int32_instead::FLAGS_verbose':
(.text+0x0): multiple definition of `RawWrite(int, char const*, unsigned long)'; logging.o (symbol from plugin):(.text+0x0): first defined here
/usr/bin/ld: lt2-logging.o (symbol from plugin): in function `FLAG__namespace_do_not_use_directly_use_DECLARE_int32_instead::FLAGS_verbose':
(.text+0x0): multiple definition of `RawClose(int)'; logging.o (symbol from plugin):(.text+0x0): first defined here
/usr/bin/ld: lt2-logging.o (symbol from plugin): in function `FLAG__namespace_do_not_use_directly_use_DECLARE_int32_instead::FLAGS_verbose':
(.text+0x0): multiple definition of `FLAG__namespace_do_not_use_directly_use_DECLARE_int32_instead::FLAGS_noverbose'; logging.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

**Comment by barracuda156** [comment] 2024-01-04 19:38
@msimberg It’s late night here, I will look into this tomorrow, I need a PowerMac and BBEdit for that :) 

If this is anything specific to Valgrind, it won’t be reproducible on MacOS PowerPC, since Valgrind is broken and never worked for it.
(LTO does not work either, by the way, but I think passing `-flto` is inconsequential, it does not break anything.)

We had been having troubles with linking of tcmalloc libs here, but with CMake build and regardless of the arch.

**Comment by alk** [comment] 2024-01-04 21:24
Ah, mystery solved. We only pull one specific stuff on i386 and ppc: https://github.com/gperftools/gperftools/blob/d5c1edf4f5fe901f40d96f4a9d4914f651742c88/src/base/vdso_support.h#L68

So that pulls vdso bits which pull RunningOnValgrind which trigger the .a ordering issue. And on other platforms, this doesn't happen and we're good.

**Comment by alk** [comment] 2024-01-05 01:01
Fix is coming soon. Let me document what is the .a ordering issue we're having here. I will refer from commit message to this post.

Sadly I am not able to link to this specific paragraph of GNU ld docs, but anyone should be able to find it themselves. Go to "Command-line options" section and search for description of -l flag. It'll have this (I am quoting):

```
     The linker will search an archive only once, at the location where
     it is specified on the command line.  If the archive defines a
     symbol which was undefined in some object which appeared before the
     archive on the command line, the linker will include the
     appropriate file(s) from the archive.  However, an undefined symbol
     in an object appearing later on the command line will not cause the
     linker to search the archive again.

     See the ‘-(’ option for a way to force the linker to search
     archives multiple times.

     You may list the same archive multiple times on the command line.
```

Or see documentation of --start-group flag. And related option worth knowing about is --whole-archive.

I.e. linking with libfoo.a is different than mentioning every .o from that library on linking command line. That is, linker assumes we only want to pull those .o-s that are necessary. Because way back when dynamic libraries didn't exist, is how you linked to statically linked libc and libm etc (i.e. you want to only pull libc and libm bits that you actually use, rather than all of it).

Normally when there are no mutually recursive dependencies between .a libraries, you simply mention them in the order with dependencies last. I.e. if you need libfoo and libbar, but libfoo needs libbar, then you do "libfoo libbar" in that order. But in our case we do have mutual dependency between liblogging.a and libsysinfo.a.

We could have used liblogging.a and libsysinfo.a twice as noted above. Or we could have used --whole-archive. But the duplication is silently removed by libtool. And the later is GNU ld feature, so potentially less portable than we need.

This specific issue was introduced in commit 4d1a9e92266f2109d9f535ad65434924765a2456 (so after 2.13 and before 2.14).

**Comment by alk** [comment] 2024-01-05 01:17
Okay. Should be fixed on master. Please test and ack or nack.

**Comment by spotaws** [comment] 2024-01-05 13:25
Looks good on my end, thanks for the quick fix!

**Comment by msimberg** [comment] 2024-01-08 09:24
@alk I can confirm that the spack CI successfully built 2.15 on PPC (https://github.com/spack/spack/pull/41984, can't comment about i386, but I guess it should work trivially there as well if it works on PPC). Thanks for the very quick fix!

**Closed** 2024-02-05 14:47 UTC
Labels: bug, alk-wants-this-soon, fixed-in-2.15
