### ISSUE TITLE
./configure does not set c++11 compiler flag which can cause build failures

### ISSUE THREAD

**Issue by volviq** [gperftools/gperftools#889] opened 2017-05-19 08:13 UTC
src/sampler.cc includes  "<limits>" to get the definition for "SIZE_MAX". 
On some systems and gcc compiler versions, this only works if the flag "-std=c++11" is passed to the compiler.
Instead of requiring to run:
CXXFLAGS="-std=c++11" ./configure
the ./configure script could automatically set this flag.
Alternatively it may be possible to "#include "stdint.h"" in case SIZE_MAX is not defined.

This problem was discovered in openSUSE Linux 11 with g++ 4.9.2. and the release: gperftools-2.5.91
The same compiler on Ubuntu 14 did not show this problem.

**Comment by alk** [comment] 2017-05-19 15:19
Thanks for reporting. Indeed, I don't have intention of forcing c++11 yet. This is duplicate of  #887.

**Closed by alk** 2017-05-19 15:19 UTC
