### ISSUE TITLE
GCC flag -flto wrecks havok on tcmalloc symbols

### ISSUE THREAD

**Issue by kreuzerkrieg** [gperftools/gperftools#1069] opened 2018-12-05 08:09 UTC
It took me a whole day to find the flag that prevented from tcmalloc to link into my binary properly. Looks like that a part of `glibc` stuff was overridden, like `free` (it was failing on "invalid pointer") but `malloc` was still going to `glibc` implementation.
By elimination I found that it is the `-flto` flag. No idea why. Does anyone experience such a behavior?

**Comment by alk** [comment] 2019-04-07 21:49
Interesting. I assume you linked tcmalloc with rest of your program statically? Google internal binaries are routinely built with some sort of lto (not -flto though). While gperftools has diverged, I am not aware of anything that would break LTO.

**Comment by kreuzerkrieg** [comment] 2019-04-08 05:51
dynamically
in the end I just dropped -flto since I failed to solve the problem, and by the way `jemalloc` exhibited same behavior

**Comment by ravenAtSafe** [comment] 2020-09-15 18:23
We have tripped over something that seems related.  Our executable links to tcmalloc_minimal.so.  If we enable LTO for the **executable** we get instability in GDAL shutdown.

Other random details, in case it helps

- GDAL does some tricky things with threads and memory
- Adding LTO to the executable makes a **huge** performance difference to tcmalloc free (as invoked by .so libs, indirectly) in Ubuntu 18.04, but not Ubuntu 20.04
- tcmalloc is v2.7 on 20.04 and v2.5.2 on 18.04
- GDAL instability due to tcmalloc + LTO has been seen in Ubuntu 18.04; we are in the process of confirming on 20.04
- Every .so in our app still has LTO enabled, apparently without causing trouble (which makes sense, given that they aren't linking against tcmalloc)

**Comment by alk** [comment] 2020-12-20 02:20
Perhaps best way to make some progress here would be if someone can post or link testing program or similar. Is any of those "lto-suffering" programs free software?

**Comment by alk** [comment] 2023-07-03 02:50
BTW there were concrete problems reported at #1358 which ended up just artifacts of linking tests and preventing "bad" inlinings. This is now fixed. Doesn't look like it should affect whatever case is reported here, but I'll note just in case.

**Comment by alk** [comment] 2023-07-09 21:34
Also BTW if you guys care so much about perf that you do LTO (I assume profile guided too), then you really should consider linking tcmalloc statically and making it part of LTO thingy. LTO itself won't help tcmalloc, we already do ~all required things inlined etc, but avoiding PLT indirection for malloc/free/etc calls would buy you nontrivial perf wins (well, if you app mallocs often enough).

I am closing this for now. Please reopen with specific instructions how to reproduce.

**Closed by alk** 2023-07-09 21:34 UTC
