### ISSUE TITLE
Build error when cross compiling for target-x86_64_musl

### ISSUE THREAD

**Issue by graysky2** [gperftools/gperftools#1406] opened 2023-07-14 00:05 UTC
In building the latest commit from master, using the OpenWrt build system, I am getting this breakage error:
```
In file included from src/malloc_hook.cc:673:
src/malloc_hook_mmap_linux.h:63:39: error: 'off64_t' has not been declared
   63 |                               int fd, off64_t offset) __THROW {
      |                                       ^~~~~~~
src/malloc_hook_mmap_linux.h:152:24: error: 'off64_t' has not been declared
  152 |                int fd, off64_t offset  ) __THROW
      |                        ^~~~~~~
src/malloc_hook_mmap_linux.h:167:33: error: 'off64_t' has not been declared
  167 |                         int fd, off64_t offset) __THROW {
      |                                 ^~~~~~~
```

Complete build [log](https://gist.github.com/graysky2/a195e44bc7ee7a6078e0ebbb03389e86).
Link to [Makefile](https://github.com/graysky2/packages/blob/gperftools/libs/gperftools/Makefile) used for building.

**Comment by graysky2** [comment] 2023-07-14 00:20
> So most of these should now be fixed. except nothrow thingy. The later is hard to do semi-portably. And there is no goal of having warning-free builds for every system. And with all my respect towards clean-ness and principledness of musl, it is not major libc. So this warning is likely to stay. If that specific warning bugs you, just -Wno-XYZ it in your builds. Closing.

Can you advise on which `-Wno-XYZ` is needed in my case?

**Comment by alk** [comment] 2023-07-14 02:04
So this is actually off64_t thingy I initially wrongly assumed to be caused by you building linux syscalls (which is not true). Deduping this onto #1407

**Comment by alk** [comment] 2023-07-14 02:07
your specific issue with x86-64 should now be fixed on master

**Comment by graysky2** [comment] 2023-07-14 20:19
Thanks @alk - I just built from the latest commit but got errors:
```
src/malloc_hook_mmap_linux.h:152:24: error: 'off64_t' has not been declared
  152 |                int fd, off64_t offset  ) __THROW
      |                        ^~~~~~~
src/malloc_hook_mmap_linux.h:167:33: error: 'off64_t' has not been declared
  167 |                         int fd, off64_t offset) __THROW {
      |                                 ^~~~~~~
make[3]: *** [Makefile:5487: src/low_level_alloc_unittest-malloc_hook.o] Error 1
```
Complete build log is [here](https://gist.github.com/graysky2/986908fe78f14c3ba57f856f69024c6c).
Makefile used to build is [here](url).

**Comment by graysky2** [comment] 2023-07-21 08:38
@alk - ping, is there any more info I can provide to help you debug this?

**Comment by alk** [comment] 2023-07-21 18:00
Indeed, I messed up and somehow failed to notice (I do test on alpine from time to time). I am finishing up significant rework on this area. So off64_t will be gone for good. Just wait a bit more. Or you desperately require something working asap, just go ahead and manually typedef off64_t to be off_t, or just replace it in offending places.

**Comment by graysky2** [comment] 2023-07-21 19:34
Thanks @alk

**Closed** 2023-07-21 20:13 UTC

**Comment by graysky2** [comment] 2023-07-22 10:39
@alk - thank you, confirmed to be working on OpenWrt

**Comment by graysky2** [comment] 2023-07-31 19:14
@alk - can you create a new tagged release incorporating this fix?

**Comment by alk** [comment] 2023-08-01 00:18
Done. I was in the middle of it today when you posted this comment : )

**Comment by alk** [comment] 2023-08-01 00:19
This is rc btw, I'll do full 2.11 in about a week assuming nothing horrible is found.

**Comment by graysky2** [comment] 2023-08-01 20:04
For what it's worth I have been running https://github.com/gperftools/gperftools/commit/42dde1b883b29921ac89234369f88b133821690c for several weeks now/rock solid.

**Comment by graysky2** [comment] 2023-08-01 21:37
I did not see 2.11rc1 as a tag, can you create one?

**Comment by alk** [comment] 2023-08-02 02:30
It is tagged as 2.10.80

**Comment by graysky2** [comment] 2023-08-02 11:58
My bad, thanks.  I was expecting to see 2.11rc1 or the like.

Question: what does the tarball have a double name in it?  For example:
```
% tar tvf gperftools-gperftools-2.10.80.tar.gz |less
drwxrwxr-x root/root         0 2023-07-31 20:11 gperftools-gperftools-2.10.80/
-rw-rw-r-- root/root      3027 2023-07-31 20:11 gperftools-gperftools-2.10.80/.gitignore
...
```

**Comment by alk** [comment] 2023-08-05 17:19
Ah, this is me failing to upload .tar.gz binaries (make dist; as per usual autotools procedures produces right archives with ./configure etc). So then github "helps" by automagically uploading from git tag. Second gperftools is because we tag gperftools-x.y.z.

For RC probably not worth "fixing". But I'll try harder when doing full 2.11 release.

**Comment by graysky2** [comment] 2023-08-05 17:45
I actually worked around this by redefining the build tool's expectation for your source.  You can just keep doing it as you are doing it.

See: https://github.com/graysky2/packages/commit/7f0b61c91b925d8ecf4edb4656bb5b7916fc4e49#diff-f2c5658fb872a77a2d23b24e7cfcf01de4e8f24e730cf1702e22dbac5429d22aR10

**Comment by alk** [comment] 2023-08-05 17:55
BTW, since you appear to be doing distro packaging of some kind, can you please consider not shipping (semi-broken, unsupported) pprof that we have? Just pass --disable-deprecated-pprof to configure. Users should get (e.g. go get) pprof from https://github.com/google/pprof

Then plan is to eventually make this (not installing pprof) default, but I'd like distros to stop doing it first.

**Comment by graysky2** [comment] 2023-08-05 18:05
I am packaging gperftools as a dependency of snort.  Do you know if snort will be happy without `/usr/bin/pprof`?  It seems to run fine without it.

I patched my commit above with the following and build the package successfully.  Snort on my box seems to run fine.
```
diff --git a/libs/gperftools/Makefile b/libs/gperftools/Makefile
index 00184f16b..e872589df 100644
--- a/libs/gperftools/Makefile
+++ b/libs/gperftools/Makefile
@@ -47,7 +47,8 @@ endef
 
 CONFIGURE_ARGS += \
        --enable-frame-pointers \
-       --enable-libunwind
+       --enable-libunwind \
+       --disable-deprecated-pprof
 
 define Build/Configure
        ( cd $(PKG_BUILD_DIR); ./autogen.sh );
@@ -69,7 +70,7 @@ endef
 define Package/gperftools-runtime/install
        $(INSTALL_DIR) $(1)/usr/bin
        $(INSTALL_DATA) $(PKG_INSTALL_DIR)/usr/bin/pprof-symbolize $(1)/usr/bin/pprof-symbolize
-       $(INSTALL_DATA) $(PKG_INSTALL_DIR)/usr/bin/pprof $(1)/usr/bin/pprof
+       #$(INSTALL_DATA) $(PKG_INSTALL_DIR)/usr/bin/pprof $(1)/usr/bin/pprof
        $(INSTALL_DIR) $(1)/usr/lib
        $(INSTALL_DATA) $(PKG_INSTALL_DIR)/usr/lib/*.so* $(1)/usr/lib/
 endef
```

**Comment by alk** [comment] 2023-08-05 19:42
If gperftools (likely tcmalloc) is only used as library dependency, then pprof isn't needed. pprof is only for people to analyze and visualize profiles produced by cpu profiler, etc.
