### ISSUE TITLE
GetDIBits() API fails silently on my windows using tcmalloc as heap manager

### ISSUE THREAD

**Issue by popgo-mos** [gperftools/gperftools#710] opened 2015-09-09 09:25 UTC
Strangely, GetDIBits() it would sometimes work, seemingly at random.

**Comment by alk** [comment] 2015-09-09 15:10
We'll need a lot more details on this. Also what makes you think that it is caused by tcmalloc ?

**Comment by popgo-mos** [comment] 2015-09-10 00:46
OK, I use tcmalloc as heap manager in my Qt project. Before I use tcmalloc,
my project works well. After I search in MSDN, I find that I am not alone.
Somebody else had the same issue.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd144879(v=vs.85).aspx

2015-09-09 23:11 GMT+08:00 Aliaksey Kandratsenka (aka Aliaksei
Kandratsenka) <notifications@github.com>:

**Comment by zatrazz** [comment] 2015-09-10 17:33
Based on last message in same thread you brought up:

 > * The GDI function has an undocumented requirement for lpvBits to not straddle multiple VirtualAlloc reserve/commits (i.e. this behavior is by design).
> * The GDI function has a bug where it can't handle buffers that straddle multiple memory commits when it should be able to.
>  * The video drivers on the system have a bug such that they impose this undocumented requirement (i.e. not Microsoft's fault).

> Summary:  Given the observations below, the only safe buffer to pass to lpvBits is one that you have directly allocated using a single call to VirtualAlloc.  Do not use malloc, operator new, GlobalAlloc, HeapAlloc, or other heap allocators; they are not safe to use.

It does not seems to be a tcmalloc issue, rather a GDI one.

**Comment by alk** [comment] 2015-09-15 01:35
Thanks Adhemerval.  I couldn't express this any better. Fully agree with you and closing bug as "not a bug" since this is indeed not malloc's issue.

**Closed by alk** 2015-09-15 01:35 UTC
