### ISSUE TITLE
Cross build problem from MacOS arm64 to MacOS x86_64

### ISSUE THREAD

**Issue by sfence** [gperftools/gperftools#1552] opened 2024-08-31 09:47 UTC
Version: gperftools-2.15 source in /Users/user/Desktop/build_app/deps/gperftools-2.15

Configure: 
```
dir="/Users/user/Desktop/build_app/deps"
CFLAGS="-arch x86_64" LDFLAGS="-arch x86_64" CXXFLAGS="-arch x86_64" ./configure "--prefix=$dir/install"  "--host=x86_64-apple-darwin"
make 2>&1 | tee build_log
```

[build_log.txt](https://github.com/user-attachments/files/16824135/build_log.txt)
[config.status.txt](https://github.com/user-attachments/files/16824136/config.status.txt)

Build failed because of undefined symbols, caused as the effect of the problem bellow:

One of obj files is linked as arm64 instead of x86_64.
```
file .libs/*        
.libs/libtcmalloc_debug.4.dylib:          Mach-O 64-bit dynamically linked shared library x86_64
.libs/libtcmalloc_debug.4.dylib-master.o: Mach-O 64-bit object arm64
.libs/libtcmalloc_debug.dylib:            Mach-O 64-bit dynamically linked shared library x86_64
```

Looks like somehow `-arch x86_64` flag has not been added to the link command
for `.libs/libtcmalloc_debug.4.dylib-master.o`.

See build log lines:
```
libtool: link: g++ -std=gnu++11 -std=gnu++11 -r -keep_private_externs -nostdlib -o .libs/libtcmalloc_debug.4.dylib-master.o  src/.libs/libtcmalloc_debug_la-debugallocation.o   -Wl,-force_load,./.libs/libtcmalloc_internal.a
libtool: link: g++ -std=gnu++11 -std=gnu++11 -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libtcmalloc_debug.4.dylib .libs/libtcmalloc_debug.4.dylib-master.o  -lpthread  -momit-leaf-frame-pointer -arch x86_64 -arch x86_64   -pthread -install_name  /Users/sfence/Desktop/minetest/minetest_build_x86_64_104/deps/install/lib/libtcmalloc_debug.4.dylib -compatibility_version 10 -current_version 10.16
ld: warning: ignoring file '/Users/sfence/Desktop/minetest/minetest_build_x86_64_104/deps/gperftools-2.15/.libs/libtcmalloc_debug.4.dylib-master.o': found architecture 'arm64', required architecture 'x86_64'
```

See also `config.status` lines:
```
archive_cmds_CXX='$CC -r -keep_private_externs -nostdlib -o $lib-master.o $libobjs~$CC -dynamiclib $allow_undefined_flag -o $lib $lib-master.o $deplibs $compiler_flags -install_name $rpath/$soname $verstring'
archive_expsym_cmds_CXX='/usr/bin/sed '\''s|^|_|'\'' < $export_symbols > $output_objdir/$libname-symbols.expsym~$CC -r -keep_private_externs -nostdlib -o $lib-master.o $libobjs~$CC -dynamiclib $allow_undefined_flag -o $lib $lib-master.o $deplibs $compiler_flags -install_name $rpath/$soname $verstring $wl-exported_symbols_list,$output_objdir/$libname-symbols.expsym'
```

**Comment by alk** [comment] 2024-09-01 16:09
The issue appears to be with whatever libtool does to build shared object. To reproduce make libtcmalloc_minimal.la and you'll see:

```
/bin/sh ./libtool  --tag=CXX   --mode=link g++ -std=gnu++11 -std=gnu++17 -DNO_TCMALLOC_SAMPLES -DNO_HEAP_CHECK -DNDEBUG -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fsized-deallocation -Wthread-safety  -fno-omit-frame-pointer -momit-leaf-frame-pointer -arch x86_64 -version-info 9:16:5 -no-undefined  -lpthread  -arch x86_64 -o libtcmalloc_minimal.la -rpath /usr/local/lib src/libtcmalloc_minimal_la-tcmalloc.lo src/libtcmalloc_minimal_la-common.lo src/libtcmalloc_minimal_la-internal_logging.lo src/libtcmalloc_minimal_la-system-alloc.lo src/libtcmalloc_minimal_la-memfs_malloc.lo src/libtcmalloc_minimal_la-safe_strerror.lo src/libtcmalloc_minimal_la-central_freelist.lo src/libtcmalloc_minimal_la-page_heap.lo src/libtcmalloc_minimal_la-sampler.lo src/libtcmalloc_minimal_la-span.lo src/libtcmalloc_minimal_la-stack_trace_table.lo src/libtcmalloc_minimal_la-static_vars.lo src/libtcmalloc_minimal_la-symbolize.lo src/libtcmalloc_minimal_la-thread_cache.lo src/libtcmalloc_minimal_la-thread_cache_ptr.lo src/libtcmalloc_minimal_la-malloc_hook.lo src/libtcmalloc_minimal_la-malloc_extension.lo libcommon.la 
libtool: link: g++ -std=gnu++11 -std=gnu++17 -r -keep_private_externs -nostdlib -o .libs/libtcmalloc_minimal.4.dylib-master.o  src/.libs/libtcmalloc_minimal_la-tcmalloc.o src/.libs/libtcmalloc_minimal_la-common.o src/.libs/libtcmalloc_minimal_la-internal_logging.o src/.libs/libtcmalloc_minimal_la-system-alloc.o src/.libs/libtcmalloc_minimal_la-memfs_malloc.o src/.libs/libtcmalloc_minimal_la-safe_strerror.o src/.libs/libtcmalloc_minimal_la-central_freelist.o src/.libs/libtcmalloc_minimal_la-page_heap.o src/.libs/libtcmalloc_minimal_la-sampler.o src/.libs/libtcmalloc_minimal_la-span.o src/.libs/libtcmalloc_minimal_la-stack_trace_table.o src/.libs/libtcmalloc_minimal_la-static_vars.o src/.libs/libtcmalloc_minimal_la-symbolize.o src/.libs/libtcmalloc_minimal_la-thread_cache.o src/.libs/libtcmalloc_minimal_la-thread_cache_ptr.o src/.libs/libtcmalloc_minimal_la-malloc_hook.o src/.libs/libtcmalloc_minimal_la-malloc_extension.o   -Wl,-force_load,./.libs/libcommon.a
ld: warning: ignoring file src/.libs/libtcmalloc_minimal_la-common.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64
.. more warnings below

```

I.e. makefile invokes libtool with link mode and then libtool does libtcmalloc_minimal.4.dylib-master.o thingy for whatever reason. And fails to pass any flags.

The simplest way to workaround is to do -arch thingy in CXX.

Like this:

```
$ CXX="g++ -arch x86_64" ./configure --enable-minimal --disable-static  --host=x86_64-apple-darwin
```

How to solve this permanently I am not sure. Thing is, "canonical" way to cross compile is to have a bunch of per-target binaries. Like, x86_64-apple-darwin-{g++,ar,ld,etc}. It'll do the most right thing IMO. I don't know if you can convince Apple folk to do it. You can also surely do those binaries as simple shell/python/ruby/etc script wrappers as needed.

And finally, maybe something can be filed against libtool, but they're not very active recently anyways (or, rather, fully silent). And not sure if it is their issue too.

Closing as "done". But do feel free to reopen if you think there is more we can do on gperftools' end.

**Closed by alk** 2024-09-01 16:09 UTC

**Comment by sfence** [comment] 2024-09-01 16:29
I did more research during that time: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=72916
It comes from libtool m4 script probably.
Hopefully, they fix it soon. But go around with CXX variable looks to be a solution.

**Comment by alk** [comment] 2024-09-02 16:57
Well, as I noted above, I am not even 100% sure your bug report is entirely valid. What this step seems to be doing is linking a number of .o-s into single "master" .o file. So c- or cxx-flags would not be right thing to do there. LDFLAGS maybe. But even then, this being simply combining .o files can be argued doesn't need flags (a stretch, sure).

Most portable way would be to have canonical per-host executables rather than passing "arcane" flags for architecture. Would also make cross-building completely out-of-the-box.
