### ISSUE TITLE
Error when compiling for v2.13

### ISSUE THREAD

**Issue by starshine360** [gperftools/gperftools#1468] opened 2023-12-19 10:39 UTC
When I compile for gperftools-2.13, something is error. How can I solve it? 

My operations are:

1. `./autogen.sh`
2. `./configure --prefix=/xxx/xxx/`
3. `make`

And the gcc is 4.8.5

The error message is as below:

> src/base/sysinfo.cc: In function 'std::tuple<bool, const char*, const char*> QueryHPCEnvironment()':
src/base/sysinfo.cc:230:36: error: converting to 'std::tuple<bool, const char*, const char*>' from initializer list would use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {bool, const char (&)[7], char*&}; <template-parameter-2-2> = void; _Elements = {bool, const char*, const char*}]'
     return {false, ".rank-", envval};
                                    ^

**Comment by alk** [comment] 2023-12-19 21:53
Likely duplicate of #1432 .

But please note that 4.8.5 is way too old. Upgrade your compiler.

**Comment by alk** [comment] 2023-12-19 21:54
Expect release with the fix in next week or two. Or just get freshest from github

**Closed by alk** 2023-12-19 21:53 UTC
