### ISSUE TITLE
DebugMallocImplementation::GetAllocatedSize() incorrect for memalign blocks

### ISSUE THREAD

**Issue by paulmenage** [gperftools/gperftools#738] opened 2015-11-06 22:14 UTC
debugallocation.cc:tc_malloc_size returns an overly large allocation size when the block has been allocated with tc_memalign(). GetAllocatedSize() returns the data_size() of the originally-allocated block, which is wrong since the user-visible pointer is offset from the start of the block in order to ensure correct alignment. It should be something more like:

return  (char *)MallocBlock::FromRawPointer(p)->size2_addr() - (char *)p;

i.e. the actual distance between the end of the usable block and the user-visible pointer.

**Comment by alk** [comment] 2015-11-07 20:36
Thanks a lot for finding and reporting it. Care to submit a patch with test case and fix ?

**Comment by acmorrow** [comment] 2017-10-05 17:01
@paulmenage @alk - Any plans for a fix for this? It seems to render some of the more advanced debugging facilities like page_fence unusable.

**Comment by alk** [comment] 2023-07-10 03:48
Interesting. From quick inspection the issue is likely to be there still (despite all the work for C++14 overalligned types work...)

**Closed** 2023-07-31 20:32 UTC
Labels: alk-wants-this-soon
