### ISSUE TITLE
Crash at any free()/delete() in Debug with VS2015

### ISSUE THREAD

**Issue by LittleWhite-tb** [gperftools/gperftools#894] opened 2017-06-07 13:26 UTC
Hello,

If a project using tcmalloc is compiled using VS2015 with the option /MDd (Multi-Threaded Debug DLL), it will crash at any free()/delete.
Everything is fine in Release (even with option /MD) or in debug with option /MTd.

This can be reproduce with tcmalloc_minimal_unittest, if you change the appropriate option in the project.

(I don't have any callstack, the crash occurs in ntdll.dll.)

Is there a solution for this problem ?

Thank you.

**Comment by alk** [comment] 2017-07-02 01:28
This is known issue with the way visual studio handles C++ operator new/delete. Unfortunately, each module is built with it's own operator new/delete and when debug build is used, those implementations call some debug checking functions in MSVC C++ runtime. This approach both hurts ultimate performance, because of extra call for every operator new/delete, and makes debug allocator case hopeless.

**Comment by LittleWhite-tb** [comment] 2017-08-29 20:36
What would be your advise if I am working on a project using /MD and /MDd (option forced by dependancy libraries) and that I have a memory bug/corruption that happen only in Release, but impossible to reproduce in debug, since the memory handling is completely different because of tcmalloc not usable ?
What would be the right thing to do ?

**Comment by alk** [comment] 2017-09-23 22:08
I don't have any options for you. MSVC C debug runtime simply isn't compatible with tcmalloc patching.

Your option could be linking everything, including tcmalloc statically. But that generally requires rebuilding MSVC runtime. This is what chrome does.

**Comment by prezmek** [comment] 2018-04-18 10:15
I recently reproduced something similar with VS2017 (gperftools 2.7rc and 2.5). In RELEASE everything works fine but in DEBUG mode my app crashes.

tcmalloc_minimal_unittest shows this error:

gperftools-master\src\central_freelist.cc:333] tcmalloc: allocation failed 8192

and debugger points at ntdll.dll. Again in RELEASE this test PASSes.

Is there any patch or is there any chance it will be fixed soon?

**Comment by alk** [comment] 2018-04-23 05:46
not likely. The way we're intercepting malloc and related functions on windows is hacky and that hack doesn't work with debug mode.

**Closed** 2018-08-05 23:35 UTC
