### ISSUE TITLE
Conflicting posix_memalign exception declarations

### ISSUE THREAD

**Issue by htuch** [gperftools/gperftools#946] opened 2017-12-20 10:42 UTC
When building OSS gperftools with Google's internal Clang (crosstools), we hit the following compiler error:

```
/google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/wrappers/bin/clang++ -DHAVE_CONFIG_H -I. -I./src  -I./src    -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation  -fno-omit-frame-pointer  -fno-builtin -g -O2 -MT src/tests/tcmalloc_unittest-tcmalloc_unittest.o -MD -MP -MF src/tests/.deps/tcmalloc_unittest-tcmalloc_unittest.Tpo -c -o src/tests/tcmalloc_unittest-tcmalloc_unittest.o `test -f 'src/tests/tcmalloc_unittest.cc' || echo './'`src/tests/tcmalloc_unittest.cc
In file included from src/tests/tcmalloc_unittest.cc:87:
In file included from /google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/wrappers/bin/../../toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/algorithm:62:
In file included from /google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/wrappers/bin/../../toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/bits/stl_algo.h:66:
In file included from /google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/wrappers/bin/../../toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/random:50:
In file included from /google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/wrappers/bin/../../toolchain/bin/../lib/gcc/x86_64-grtev4-linux-gnu/4.9.x-google/../../../../x86_64-grtev4-linux-gnu/include/c++/4.9.x-google/x86_64-grtev4-linux-gnu/bits/opt_random.h:33:
In file included from /google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/installs/llvm/lib/clang/google3-trunk/include/x86intrin.h:29:
In file included from /google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/installs/llvm/lib/clang/google3-trunk/include/immintrin.h:32:
In file included from /google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/installs/llvm/lib/clang/google3-trunk/include/xmmintrin.h:39:
/google/src/files/179632290/depot/google3/third_party/crosstool/v18/llvm_unstable/installs/llvm/lib/clang/google3-trunk/include/mm_malloc.h:39:16: error: 'posix_memalign' is missing exception specification 'throw()'
extern "C" int posix_memalign(void **__memptr, size_t __alignment, size_t __size);
               ^
./src/tcmalloc.h:60:16: note: previous declaration is here
extern "C" int posix_memalign(void** ptr, size_t align, size_t size) __THROW;
               ^
src/tests/tcmalloc_unittest.cc:1347:5: warning: 'delete[]' applied to a pointer that was allocated with 'new'; did you mean 'delete'? [-Wmismatched-new-delete]
    delete[] p2;
    ^     ~~
src/tests/tcmalloc_unittest.cc:1338:16: note: allocated with 'new' here
    char* p2 = new char;
               ^
src/tests/tcmalloc_unittest.cc:1359:5: warning: 'delete[]' applied to a pointer that was allocated with 'new'; did you mean 'delete'? [-Wmismatched-new-delete]
    delete[] p2;
    ^     ~~
src/tests/tcmalloc_unittest.cc:1338:16: note: allocated with 'new' here
    char* p2 = new char;
               ^
2 warnings and 1 error generated.
make: *** [src/tests/tcmalloc_unittest-tcmalloc_unittest.o] Error 1
```

It looks like `posix_memalign` is defined at least twice, once with a exception specifier (by tcmalloc) and once without (by glibc). 

It seems that the guard against redefinition in https://github.com/gperftools/gperftools/blob/master/src/tcmalloc.h#L59 is on `HAVE_POSIX_MEMALIGN_SYMBOL`. However, this is not set anywhere I can see. Instead, in the `configure.status`, I notice there exists `HAVE_DECL_POSIX_MEMALIGN`. Is this what should be used instead?

If I run `./configure` with `CXXFLAGS="-DHAVE_POSIX_MEMALIGN_SYMBOL=1"`, things build as expected.

**Comment by htuch** [comment] 2018-02-04 03:51
@alk not sure, we've actually stopped using that particular Clang toolchain, so it's not a huge issue for us anymore.

**Comment by alk** [comment] 2018-02-04 04:55
So I can close it then?

**Comment by bgemmill** [comment] 2018-03-23 23:04
Please leave this open, as it still affects clang-6 users. On a fresh checkout of tag gperftools-2.6.3, I see this:
```
/usr/include/clang/6.0.0/include/mm_malloc.h:39:16: error: 'posix_memalign' is missing exception specification 'throw()'
extern "C" int posix_memalign(void **__memptr, size_t __alignment, size_t __size);
               ^
./src/tcmalloc.h:60:16: note: previous declaration is here
extern "C" int posix_memalign(void** ptr, size_t align, size_t size) __THROW;
```

I'm coming at this from cmake, where I can reproduce fairly regularly with:
```
    include(ExternalProject)
    ExternalProject_Add(
            dependency-gperftools
            GIT_REPOSITORY https://github.com/gperftools/gperftools
            GIT_TAG gperftools-${GPERFTOOLS_VERSION}
            UPDATE_COMMAND "./autogen.sh"
            CONFIGURE_COMMAND ./configure --prefix=${GPERFTOOLS_ROOT}
            BUILD_COMMAND ""
            BUILD_IN_SOURCE true
            INSTALL_COMMAND $(MAKE) install
            INSTALL_DIR ${GPERFTOOLS_ROOT}
    )
```

**Comment by alk** [comment] 2018-03-24 22:31
I am still not able to reproduce. Running Debian Sid.

E.g.: 

./autogen.sh && ./configure --prefix=/root/gpt CXX=clang++-6.0 CC=clang-6.0 CXXFLAGS='-O2 -ggdb3 -stdlib=libc++'

I do believe that sometimes this stuff happens, but need help debugging and reproducing further. What kind of OS is that ?

**Comment by bgemmill** [comment] 2018-03-24 23:20
This is a docker image of ubuntu 16.04 with the [clang-6 deb repo](https://apt.llvm.org).

I'm not sure if this is the issue, but a difference that stands out from your command line is I'm using libstdc++ rather than libc++.

**Comment by alk** [comment] 2018-03-25 04:26
Much thanks! It did the trick.

Looks like that clang 6 from their repo is doing something as part of installation that write mm_malloc.h that cleans up that throw(). Anyways, I should have a fix now. Let me know it does not.

**Closed by alk** 2018-03-25 04:26 UTC
