### ISSUE TITLE
Build fails on Alpine linux 3.7

### ISSUE THREAD

**Issue by klwilson227** [gperftools/gperftools#984] opened 2018-04-14 17:26 UTC
I have pulled the latest docker image of alpine currently 3.7. 
I have added the following packages
RUN apk update && apk add linux-headers gcc g++ gfortran python git cmake make vim bash tar gdb py2-numpy py-numpy-dev cython cython-dev py-setuptools py2-pip automake autoconf libtool
I cloned the latest git repository for gperftools. 

autogen.sh
configure
make

the result is a compilation failure with duplicate mmap definitions. See below:

bash-4.4# make
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src  -I./src   -DNO_TCMALLOC_SAMPLES -DNO_HEAP_CHECK -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc  -Wno-unused-result -fsized-deallocation   -DNO_FRAME_POINTER -g -O2 -MT src/libtcmalloc_minimal_internal_la-malloc_hook.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_internal_la-malloc_hook.Tpo -c -o src/libtcmalloc_minimal_internal_la-malloc_hook.lo `test -f 'src/malloc_hook.cc' || echo './'`src/malloc_hook.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SAMPLES -DNO_HEAP_CHECK -DNDEBUG -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized-deallocation -DNO_FRAME_POINTER -g -O2 -MT src/libtcmalloc_minimal_internal_la-malloc_hook.lo -MD -MP -MF src/.deps/libtcmalloc_minimal_internal_la-malloc_hook.Tpo -c src/malloc_hook.cc  -fPIC -DPIC -o src/.libs/libtcmalloc_minimal_internal_la-malloc_hook.o
In file included from src/malloc_hook.cc:686:0:
src/malloc_hook_mmap_linux.h:63:39: error: '__off64_t' has not been declared
                               int fd, __off64_t offset) __THROW {
                                       ^~~~~~~~~
src/malloc_hook_mmap_linux.h:145:24: error: '__off64_t' has not been declared
                int fd, __off64_t offset  ) __THROW
                        ^~~~~~~~~
In file included from src/malloc_hook.cc:41:0:
src/malloc_hook_mmap_linux.h:144:9: error: conflicting declaration of C function 'void* mmap(void*, size_t, int, int, int, int)'
   void* mmap64(void *start, size_t length, int prot, int flags,
         ^
/usr/include/sys/mman.h:81:7: note: previous declaration 'void* mmap(void*, size_t, int, int, int, off_t)'
 void *mmap (void *, size_t, int, int, int, off_t);
       ^~~~
In file included from src/malloc_hook.cc:686:0:
src/malloc_hook_mmap_linux.h:147:9: error: conflicting declaration of C function 'void* mmap(void*, size_t, int, int, int, off_t)'
   void* mmap(void *start, size_t length,int prot, int flags,
         ^~~~
In file included from src/malloc_hook.cc:41:0:
src/malloc_hook_mmap_linux.h:144:9: note: previous declaration 'void* mmap(void*, size_t, int, int, int, int)'
   void* mmap64(void *start, size_t length, int prot, int flags,
         ^
In file included from src/malloc_hook.cc:686:0:
src/malloc_hook_mmap_linux.h:160:33: error: '__off64_t' has not been declared
                         int fd, __off64_t offset) __THROW {
                                 ^~~~~~~~~
src/malloc_hook_mmap_linux.h: In function 'void* mmap(void*, size_t, int, int, int, off_t)':
src/malloc_hook_mmap_linux.h:173:18: error: conflicting declaration of C function 'void* mmap(void*, size_t, int, int, int, off_t)'
 extern "C" void* mmap(void *start, size_t length, int prot, int flags,
                  ^~~~
In file included from src/malloc_hook.cc:41:0:
src/malloc_hook_mmap_linux.h:159:18: note: previous declaration 'void* mmap(void*, size_t, int, int, int, int)'
 extern "C" void* mmap64(void *start, size_t length, int prot, int flags,
                  ^
make: *** [Makefile:4893: src/libtcmalloc_minimal_internal_la-malloc_hook.lo] Error 1

This problem also happens on older versions of the source on the latest alpine linux. 
I am new to this code/library and happy to . do some hunting/debugging if I can get some pointers as to where to look. I suspect that there are -D defines that are not set properly for the environment leading to the duplicates. 

Any help would be appreciated.

**Comment by alk** [comment] 2018-04-15 05:51
This seems duplicate of issue #693

**Closed by alk** 2018-04-15 05:51 UTC
