### ISSUE TITLE
OS X 10.11 Xcode 7.3 build failure: operator delete(void*, unsigned long)

### ISSUE THREAD

**Issue by ilovezfs** [gperftools/gperftools#794] opened 2016-04-17 13:13 UTC
On El Capitan with Xcode 7.3, the build (2.5 and HEAD) fails.

```
...
libtool: link: (cd .libs/libtcmalloc_minimal_internal.lax/libspinlock.a && ar x "/private/tmp/gperftools20160417-8209-1v8q32c/gperftools-2.5/./.libs/libspinlock.a")
libtool: link: (cd .libs/libstacktrace.lax/libsysinfo.a && ar x "/private/tmp/gperftools20160417-8209-1v8q32c/gperftools-2.5/./.libs/libsysinfo.a")
Undefined symbols for architecture x86_64:
  "operator delete(void*, unsigned long)", referenced from:
      ProcMapsIterator::~ProcMapsIterator() in libsysinfo.a(sysinfo.o)
      ProcMapsIterator::~ProcMapsIterator() in libsysinfo.a(sysinfo.o)
      tcmalloc::FillProcSelfMaps(char*, int, bool*) in libsysinfo.a(sysinfo.o)
      tcmalloc::DumpProcSelfMaps(int) in libsysinfo.a(sysinfo.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [low_level_alloc_unittest] Error 1
make: *** Waiting for unfinished jobs....
libtool: link: (cd .libs/libtcmalloc_minimal_internal.lax/libsysinfo.a && ar x "/private/tmp/gperftools20160417-8209-1v8q32c/gperftools-2.5/./.libs/libsysinfo.a")
libtool: link: (cd .libs/libstacktrace.lax/liblogging.a && ar x "/private/tmp/gperftools20160417-8209-1v8q32c/gperftools-2.5/./.libs/liblogging.a")
libtool: link: ar cru .libs/libstacktrace.a src/.libs/stacktrace.o src/base/.libs/elf_mem_image.o src/base/.libs/vdso_support.o   .libs/libstacktrace.lax/libspinlock.a/atomicops-internals-x86.o .libs/libstacktrace.lax/libspinlock.a/spinlock.o .libs/libstacktrace.lax/libspinlock.a/spinlock_internal.o  .libs/libstacktrace.lax/libsysinfo.a/sysinfo.o  .libs/libstacktrace.lax/liblogging.a/dynamic_annotations.o .libs/libstacktrace.lax/liblogging.a/logging.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libstacktrace.a(elf_mem_image.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libstacktrace.a(vdso_support.o) has no symbols
...
```

More complete log here: https://gist.github.com/ilovezfs/fe7f19bb3e25918d6e18c4a532588c8d

And this is from a HEAD build:
https://gist.github.com/2329e4269da7bea663254444cd234957

Reference: https://github.com/Homebrew/homebrew-core/pull/383

**Comment by ilovezfs** [comment] 2016-04-18 09:14
Filtering out ` -fsized-deallocation` fixes this. With Xcode 7.2.1 this is detected by gperftools configure as unsupported, whereas with Xcode 7.3 it is detected as supported. I'm not sure what the real bug is, but that is the proximate cause of the build failure.

**Comment by ilovezfs** [comment] 2016-05-13 05:34
@alk This seems to be caused by https://github.com/gperftools/gperftools/commit/782165fa7f2c49d6a67c2415626a1f215cc21ac2

**Comment by alk** [comment] 2016-06-26 02:08
Thanks. So I've got similarly looking report in issue #804. But since I am not able to reproduce any of the problems (no osx and clang-3.8 works for me nicely on gnu/linux), I am not able to fix it.

Should we just disable linking sized delete when we're on OSX? Can you please test it and post a patch?

**Comment by ryandesign** [comment] 2018-03-10 00:09
This is still a problem with 2.6.3 on OS X 10.11 only (not older or newer). Here is a [build log from MacPorts](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/50121/steps/install-port/logs/stdio).

**Comment by alk** [comment] 2018-03-10 20:13
Please test latest commit on master branch. I think it should be fixed.

**Comment by ryandesign** [comment] 2018-03-11 02:50
Ah, you mean d7be9385609328a03c5cfe775473a7dc8e014fd3. I don't have a system with Xcode 7.3 to test on at the moment. I can't reproduce the problem on OS X 10.10 with Xcode 7.2.1, nor on OS X 10.11 with Xcode 8.2.1. And for the MacPorts OS X 10.11 build server, which currently uses Xcode 7.3.1, I already worked around the problem using a [different patch](https://github.com/macports/macports-ports/blob/49f60837b6376cbddb73140fbd8c4ec35b292a74/devel/gperftools/files/patch-build-fix-15.diff).

**Comment by RJVB** [comment] 2018-04-13 08:07
gperftools has been updated to 2.6.90; Ryan's patch no longer applies but is it still required?

FWIW, can this be related to the fact that "older" libc++abi versions didn't have the sized new and delete but instead relied on the compiler converting them to (I think) regular new and delete? That's an issue you also run into when coercing g++ to use a libc++ older than 4.0 . It would also explain why the issue cannot be reproduced with clang on Linux : clang uses libstdc++ there.

**Comment by alk** [comment] 2018-04-23 05:44
Should not be necessary any more. But please let us know vanilla gperftools still fails to build for you.

**Comment by RJVB** [comment] 2018-04-24 12:15
Vanilla builds fine on my OS X version; cannot speak for 10.11 and later though.

**Closed** 2023-07-10 03:25 UTC
