### ISSUE TITLE
Tcmalloc stats wrong bug

### ISSUE THREAD

**Issue by happy457** [gperftools/gperftools#1091] opened 2019-03-08 09:16 UTC
We use older version tcmalloc,  now we found a problem: my machine total memory is 192G, but tcmalloc stats show application memory more than machine memory size.
MALLOC:   418422825216 (399039.1 MiB) Bytes in use by application
MALLOC: +     10625024 (   10.1 MiB) Bytes in page heap freelist
MALLOC: +     58296456 (   55.6 MiB) Bytes in central cache freelist
MALLOC: +            0 (    0.0 MiB) Bytes in transfer cache freelist
MALLOC: +    251655800 (  240.0 MiB) Bytes in thread cache freelists
MALLOC: +   1358753944 ( 1295.8 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: = 420102156440 (400640.6 MiB) Actual memory used (physical + swap)
MALLOC: + 637603299328 (608065.9 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: = 1057705455768 (1008706.5 MiB) Virtual address space used
MALLOC:
MALLOC:         519659              Spans in use
MALLOC:           1049              Thread heaps in use
MALLOC:           8192              Tcmalloc page size

I use command: top to see my process use memory about 2G.

**Comment by alk** [comment] 2019-04-07 21:38
This is possible if your program is allocating very large arrays but doesn't use their full capacity. I.e. kernel will only lazily populate allocated memory. So it is possible to malloc many tens of gigs (well, with suitably enabled memory overcommit) but have RSS not affected at all.

Closing as not a bug. But if you have evidence it is indeed some sort of stats bug in gperftools, please post it. Ideally post a program to reproduce the issue.

**Closed by alk** 2019-04-07 21:38 UTC
