### ISSUE TITLE
ubuntu 18.04 cross compiling for armhf produces broken libtcmalloc_minimal.so (was: Cross compile armv7 fails to link: Bad value)

### ISSUE THREAD

**Issue by dprogm** [gperftools/gperftools#1412] opened 2023-08-01 08:48 UTC
Steps done:
1. Install the `toolchain arm-linux-gnueabihf`, all binaries are accessible through the `$PATH` 
2. Try to build `libtcmalloc.so`
```bash
./autogen.sh
./configure --host=arm-linux-gnueabihf
make 
```
Error thrown:
```bash
/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/bin/ld: .libs/malloc_bench_shared: hidden symbol `pthread_atfork' in /usr/arm-linux-gnueabihf/lib/libpthread_nonshared.a(pthread_atfork.oS) is referenced by DSO
/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/bin/ld: final link failed: Bad value
```

It seems to build `libtcmalloc.a`. I can see it under `.lib`. Can I just ignore the failure?

**Comment by dprogm** [comment] 2023-08-02 04:51
Using
```bash
arm-linux-gnueabihf-gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
```
Maybe 7.5.0 is too old.
[config.log](https://github.com/gperftools/gperftools/files/12236079/config.log)

**Comment by alk** [comment] 2023-08-05 19:35
This is really odd. I am able to reproduce in docker with ubuntu 18.04. Indeed, libtcmalloc_minimal.so is unusable (but static one works, somehow). For some reason our usage of pthread_atfork from inside .so fails to link.

It does appear to be something broken with how we (or libtool we have) produced .so, since the logic of this atfork business is each .so module needs to get it's own copy from libc_nonshared thingy.

**Comment by alk** [comment] 2023-08-05 19:47
BTW you can work around for now by adding -DTCMALLOC_NO_ATFORK to CPPFLAGS

**Comment by alk** [comment] 2023-08-05 20:11
Well, it does look like whatever libtool chooses to do when linking .so isn't working specifically in this specific case. It does plenty of "magic" -L flags, -nostdlib, passes startup .o manually etc. I see it doing ~same stuff on my box without cross compiling, so probably "normal" behavior for libtool.

For this simple test:

```
#include <pthread.h>

int my_atfork(void (*fn)(void), void (*fn2)(void)) {
    return pthread_atfork(fn, fn2, fn2);
}
```

When I produce .so manually (all of that on ubuntu 18.04 as noted above):

```
# arm-linux-gnueabihf-gcc -fPIC -DPIC -shared -o test-atfork.so -pthread -Wall -O2 -ggdb3 test-atfork.c
```

It does the right thing. I.e. objdumping test-atfork.so has __register_atfork dependency (right one and intended by glibc).

And repeating what libtool does

```
# arm-linux-gnueabihf-gcc  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/crti.o /usr/lib/gcc-cross/arm-linux-gnueabihf/7/crtbeginS.o test-atfork.c  -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7 -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib -L/lib/../lib -L/usr/lib/arm-linux-gnueabihf -L/usr/lib/../lib -L/usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc-cross/arm-linux-gnueabihf/7/crtendS.o /usr/lib/gcc-cross/arm-linux-gnueabihf/7/../../../../arm-linux-gnueabihf/lib/../lib/crtn.o  -g -O2   -pthread -o test-atfork.so
```

produces "broken" .so. I.e. that broken .so wants pthread_atfork instead of register atfork thingy.

I am not sure why specifically it fails on this specific version(s) of stuff.

But I cannot be in the business of debugging basic tooling. Either do workaround as noted above, or use newer tools (at least debian sid doesn't have same bug), or file bug(s) to our OS vendor.

Closing as "it is not our bug", as noted above. Do reopen if you disagree or something.

**Closed by alk** 2023-08-05 20:11 UTC
