### ISSUE TITLE
sys/mman error

### ISSUE THREAD

**Issue by SKIYET** [gperftools/gperftools#1182] opened 2020-03-19 02:16 UTC
Dear

Yesterday I cross compile tcmalloc for another program on my server.
The program told me "fatal error: sys/mman.h: No such file or directory".
I  found this problem has been a long time , you ca see it in this issue"https://github.com/gperftools/gperftools/issues/1108#issue-434609999".
But in your 2.7.9 package, this issue is still not solved in debian and ubuntu.

Log:

x86_64-w64-mingw32-g++-posix -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DNO_TCMALLOC_SA MPLES -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-builtin-malloc -fno-b uiltin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-builtin-memalign - fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused-result -fsized -deallocation -faligned-new -DNO_FRAME_POINTER -fno-builtin -g -O2 -MT src/tests/tcmalloc_mini mal_unittest-testutil.o -MD -MP -MF src/tests/.deps/tcmalloc_minimal_unittest-testutil.Tpo -c - o src/tests/tcmalloc_minimal_unittest-testutil.o test -f 'src/tests/testutil.cc' || echo './' src/tests/testutil.cc
src/maybe_threads.cc:62:7: warning: ‘int pthread_key_create(pthread_key_t*, void ()(void))’ r edeclared without dllimport attribute after being referenced with dll linkage
int pthread_key_create (pthread_key_t*, void ()(void))
^~~~~~~~~~~~~~~~~~
src/maybe_threads.cc:64:7: warning: ‘int pthread_key_delete(pthread_key_t)’ redeclared without dllimport attribute after being referenced with dll linkage
int pthread_key_delete (pthread_key_t)
^~~~~~~~~~~~~~~~~~
src/maybe_threads.cc:66:9: warning: ‘void* pthread_getspecific(pthread_key_t)’ redeclared witho ut dllimport attribute after being referenced with dll linkage
void pthread_getspecific(pthread_key_t)
^~~~~~~~~~~~~~~~~~~
src/maybe_threads.cc:68:7: warning: ‘int pthread_setspecific(pthread_key_t, const void)’ redec lared without dllimport attribute after being referenced with dll linkage
int pthread_setspecific(pthread_key_t, const void*)
^~~~~~~~~~~~~~~~~~~
src/maybe_threads.cc:70:7: warning: ‘int pthread_once(pthread_once_t*, void (*)())’ redeclared without dllimport attribute after being referenced with dll linkage
int pthread_once(pthread_once_t , void ()(void))
^~~~~~~~~~~~
src/tests/tcmalloc_unittest.cc:80:10: fatal error: sys/mman.h: No such file or directory
#include <sys/mman.h> // for testing mmap hooks
^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6137: src/tests/tcmalloc_minimal_unittest-tcmalloc_unittest.o] Error 1
make: *** Waiting for unfinished jobs....
libtool: compile: x86_64-w64-mingw32-g++-posix -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./sr c -DNO_TCMALLOC_SAMPLES -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -fno-built in-malloc -fno-builtin-free -fno-builtin-realloc -fno-builtin-calloc -fno-builtin-cfree -fno-bu iltin-memalign -fno-builtin-posix_memalign -fno-builtin-valloc -fno-builtin-pvalloc -Wno-unused -result -fsized-deallocation -faligned-new -DNO_FRAME_POINTER -g -O2 -MT src/maybe_threads.lo - MD -MP -MF src/.deps/maybe_threads.Tpo -c src/maybe_threads.cc -o src/maybe_threads.o >/dev/nul l 2>&1
mv -f src/tests/.deps/tcmalloc_minimal_unittest-testutil.Tpo src/tests/.deps/tcmalloc_minimal_u nittest-testutil.Po

**Comment by alk** [comment] 2020-03-23 08:14
Lets make it duplicate of issue #1108

**Closed by alk** 2020-03-23 08:14 UTC
